FROM ubuntu:noble AS builder

ARG PIP_INDEX_URL
ARG PIP_TRUSTED_HOST
ENV PIP_INDEX_URL=${PIP_INDEX_URL}
ENV PIP_TRUSTED_HOST=${PIP_TRUSTED_HOST}

# TODO: use piwheels for armv7l specifically until/if ever mainline wheels available.
RUN if [ "$(uname -m)" = "armv7l" ] ; then echo "using piwheels" ; /bin/echo -e "[global]\nextra-index-url=https://www.piwheels.org/simple\n" > /etc/pip.conf ; fi

COPY . /faucetconfrpc
WORKDIR /faucetconfrpc

RUN apt-get update && apt-get install -y curl python3-dev gcc git g++ libc6-dev libyaml-dev libffi-dev libxml2-dev libxslt-dev make python3-pip libssl-dev openssl pkg-config
RUN --security=insecure mkdir -p /root/.cargo && chmod 777 /root/.cargo && mount -t tmpfs none /root/.cargo && pip3 install --no-cache-dir "cryptography"=="$(grep cryptography pyproject.toml | grep -Eo '\"[0-9\.]+' | sed 's/\"//g')"
RUN MAKEFLAGS="-j $(nproc)" pip install --break-system-packages . -v

FROM ubuntu:noble

RUN apt-get update && apt-get install -y python3 iproute2 libatomic1 libssl1* openssl

COPY --from=builder /usr/local /usr/local
RUN python3 -c "from faucetconfrpc.faucetconfrpc_client_lib import FaucetConfRpcClient"
RUN faucetconfrpc_client --help
RUN faucetconfrpc_server --help
RUN ss --help

EXPOSE 59999

ENTRYPOINT ["faucetconfrpc_server"]
HEALTHCHECK --interval=30s CMD ss -tln|grep -q 59999 || exit 1
