FROM python:3.10-slim as builder

ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install -y iproute2 python3-dev gcc git g++ libc6-dev libyaml-dev libffi-dev libxslt-dev libxml2-dev make curl libssl-dev
RUN pip3 install -U pip
# TODO: to build wheels for cryptography, if necessary
# TODO: also work around 64/32 bit qemu issue for rustc.
ENV CARGO_HOME /dev/shm
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && \
  cp $CARGO_HOME/bin/* /usr/local/bin && \
  rustc --version && \
  pip install cryptography --no-binary cryptography
# TODO: fails unless installed by itself.
RUN pip3 install pynacl --no-binary pynacl
# TODO: wheels on non-x86 workaround with --no-binary: https://github.com/grpc/grpc/issues/27512
RUN pip install --upgrade --force-reinstall grpcio grpcio-tools --no-binary grpcio,grpcio-tools

COPY . /faucetconfrpc
WORKDIR /faucetconfrpc

RUN pip3 --no-cache-dir install .

FROM python:3.10-slim
COPY --from=builder /usr/local /usr/local

RUN python3 -c "from faucetconfrpc.faucetconfrpc_client_lib import FaucetConfRpcClient"
RUN faucetconfrpc_client --help
RUN faucetconfrpc_server --help

EXPOSE 59999

ENTRYPOINT ["faucetconfrpc_server"]
HEALTHCHECK --interval=30s CMD ss -tln|grep -q 59999 || exit 1
