# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: faucetconfrpc.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='faucetconfrpc.proto',
  package='faucetconfserver',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x13\x66\x61ucetconfrpc.proto\x12\x10\x66\x61ucetconfserver\"/\n\x14GetConfigFileRequest\x12\x17\n\x0f\x63onfig_filename\x18\x01 \x01(\t\")\n\x12GetConfigFileReply\x12\x13\n\x0b\x63onfig_yaml\x18\x01 \x01(\t\"S\n\x14SetConfigFileRequest\x12\x17\n\x0f\x63onfig_filename\x18\x01 \x01(\t\x12\x13\n\x0b\x63onfig_yaml\x18\x02 \x01(\t\x12\r\n\x05merge\x18\x03 \x01(\x08\"\x14\n\x12SetConfigFileReply\"M\n\x18\x44\x65lConfigFromFileRequest\x12\x17\n\x0f\x63onfig_filename\x18\x01 \x01(\t\x12\x18\n\x10\x63onfig_yaml_keys\x18\x02 \x01(\t\"\x18\n\x16\x44\x65lConfigFromFileReply2\xc1\x02\n\x10\x46\x61ucetConfServer\x12_\n\rGetConfigFile\x12&.faucetconfserver.GetConfigFileRequest\x1a$.faucetconfserver.GetConfigFileReply\"\x00\x12_\n\rSetConfigFile\x12&.faucetconfserver.SetConfigFileRequest\x1a$.faucetconfserver.SetConfigFileReply\"\x00\x12k\n\x11\x44\x65lConfigFromFile\x12*.faucetconfserver.DelConfigFromFileRequest\x1a(.faucetconfserver.DelConfigFromFileReply\"\x00\x62\x06proto3'
)




_GETCONFIGFILEREQUEST = _descriptor.Descriptor(
  name='GetConfigFileRequest',
  full_name='faucetconfserver.GetConfigFileRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='config_filename', full_name='faucetconfserver.GetConfigFileRequest.config_filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=88,
)


_GETCONFIGFILEREPLY = _descriptor.Descriptor(
  name='GetConfigFileReply',
  full_name='faucetconfserver.GetConfigFileReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='config_yaml', full_name='faucetconfserver.GetConfigFileReply.config_yaml', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=131,
)


_SETCONFIGFILEREQUEST = _descriptor.Descriptor(
  name='SetConfigFileRequest',
  full_name='faucetconfserver.SetConfigFileRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='config_filename', full_name='faucetconfserver.SetConfigFileRequest.config_filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='config_yaml', full_name='faucetconfserver.SetConfigFileRequest.config_yaml', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='merge', full_name='faucetconfserver.SetConfigFileRequest.merge', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=216,
)


_SETCONFIGFILEREPLY = _descriptor.Descriptor(
  name='SetConfigFileReply',
  full_name='faucetconfserver.SetConfigFileReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=218,
  serialized_end=238,
)


_DELCONFIGFROMFILEREQUEST = _descriptor.Descriptor(
  name='DelConfigFromFileRequest',
  full_name='faucetconfserver.DelConfigFromFileRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='config_filename', full_name='faucetconfserver.DelConfigFromFileRequest.config_filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='config_yaml_keys', full_name='faucetconfserver.DelConfigFromFileRequest.config_yaml_keys', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=240,
  serialized_end=317,
)


_DELCONFIGFROMFILEREPLY = _descriptor.Descriptor(
  name='DelConfigFromFileReply',
  full_name='faucetconfserver.DelConfigFromFileReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=319,
  serialized_end=343,
)

DESCRIPTOR.message_types_by_name['GetConfigFileRequest'] = _GETCONFIGFILEREQUEST
DESCRIPTOR.message_types_by_name['GetConfigFileReply'] = _GETCONFIGFILEREPLY
DESCRIPTOR.message_types_by_name['SetConfigFileRequest'] = _SETCONFIGFILEREQUEST
DESCRIPTOR.message_types_by_name['SetConfigFileReply'] = _SETCONFIGFILEREPLY
DESCRIPTOR.message_types_by_name['DelConfigFromFileRequest'] = _DELCONFIGFROMFILEREQUEST
DESCRIPTOR.message_types_by_name['DelConfigFromFileReply'] = _DELCONFIGFROMFILEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetConfigFileRequest = _reflection.GeneratedProtocolMessageType('GetConfigFileRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETCONFIGFILEREQUEST,
  '__module__' : 'faucetconfrpc_pb2'
  # @@protoc_insertion_point(class_scope:faucetconfserver.GetConfigFileRequest)
  })
_sym_db.RegisterMessage(GetConfigFileRequest)

GetConfigFileReply = _reflection.GeneratedProtocolMessageType('GetConfigFileReply', (_message.Message,), {
  'DESCRIPTOR' : _GETCONFIGFILEREPLY,
  '__module__' : 'faucetconfrpc_pb2'
  # @@protoc_insertion_point(class_scope:faucetconfserver.GetConfigFileReply)
  })
_sym_db.RegisterMessage(GetConfigFileReply)

SetConfigFileRequest = _reflection.GeneratedProtocolMessageType('SetConfigFileRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETCONFIGFILEREQUEST,
  '__module__' : 'faucetconfrpc_pb2'
  # @@protoc_insertion_point(class_scope:faucetconfserver.SetConfigFileRequest)
  })
_sym_db.RegisterMessage(SetConfigFileRequest)

SetConfigFileReply = _reflection.GeneratedProtocolMessageType('SetConfigFileReply', (_message.Message,), {
  'DESCRIPTOR' : _SETCONFIGFILEREPLY,
  '__module__' : 'faucetconfrpc_pb2'
  # @@protoc_insertion_point(class_scope:faucetconfserver.SetConfigFileReply)
  })
_sym_db.RegisterMessage(SetConfigFileReply)

DelConfigFromFileRequest = _reflection.GeneratedProtocolMessageType('DelConfigFromFileRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELCONFIGFROMFILEREQUEST,
  '__module__' : 'faucetconfrpc_pb2'
  # @@protoc_insertion_point(class_scope:faucetconfserver.DelConfigFromFileRequest)
  })
_sym_db.RegisterMessage(DelConfigFromFileRequest)

DelConfigFromFileReply = _reflection.GeneratedProtocolMessageType('DelConfigFromFileReply', (_message.Message,), {
  'DESCRIPTOR' : _DELCONFIGFROMFILEREPLY,
  '__module__' : 'faucetconfrpc_pb2'
  # @@protoc_insertion_point(class_scope:faucetconfserver.DelConfigFromFileReply)
  })
_sym_db.RegisterMessage(DelConfigFromFileReply)



_FAUCETCONFSERVER = _descriptor.ServiceDescriptor(
  name='FaucetConfServer',
  full_name='faucetconfserver.FaucetConfServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=346,
  serialized_end=667,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetConfigFile',
    full_name='faucetconfserver.FaucetConfServer.GetConfigFile',
    index=0,
    containing_service=None,
    input_type=_GETCONFIGFILEREQUEST,
    output_type=_GETCONFIGFILEREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetConfigFile',
    full_name='faucetconfserver.FaucetConfServer.SetConfigFile',
    index=1,
    containing_service=None,
    input_type=_SETCONFIGFILEREQUEST,
    output_type=_SETCONFIGFILEREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DelConfigFromFile',
    full_name='faucetconfserver.FaucetConfServer.DelConfigFromFile',
    index=2,
    containing_service=None,
    input_type=_DELCONFIGFROMFILEREQUEST,
    output_type=_DELCONFIGFROMFILEREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FAUCETCONFSERVER)

DESCRIPTOR.services_by_name['FaucetConfServer'] = _FAUCETCONFSERVER

# @@protoc_insertion_point(module_scope)
