# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import faucetconfrpc_pb2 as faucetconfrpc__pb2


class FaucetConfServerStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Placeholder = channel.unary_unary(
                '/FaucetConfServer/Placeholder',
                request_serializer=faucetconfrpc__pb2.PlaceholderRequest.SerializeToString,
                response_deserializer=faucetconfrpc__pb2.PlaceholderReply.FromString,
                )


class FaucetConfServerServicer(object):
    """Missing associated documentation comment in .proto file"""

    def Placeholder(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FaucetConfServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Placeholder': grpc.unary_unary_rpc_method_handler(
                    servicer.Placeholder,
                    request_deserializer=faucetconfrpc__pb2.PlaceholderRequest.FromString,
                    response_serializer=faucetconfrpc__pb2.PlaceholderReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FaucetConfServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FaucetConfServer(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def Placeholder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FaucetConfServer/Placeholder',
            faucetconfrpc__pb2.PlaceholderRequest.SerializeToString,
            faucetconfrpc__pb2.PlaceholderReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
