# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: faucetconfrpc.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='faucetconfrpc.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x13\x66\x61ucetconfrpc.proto\")\n\x12PlaceholderRequest\x12\x13\n\x0bplaceholder\x18\x01 \x01(\t\"\'\n\x10PlaceholderReply\x12\x13\n\x0bplaceholder\x18\x01 \x01(\t2K\n\x10\x46\x61ucetConfServer\x12\x37\n\x0bPlaceholder\x12\x13.PlaceholderRequest\x1a\x11.PlaceholderReply\"\x00\x62\x06proto3'
)




_PLACEHOLDERREQUEST = _descriptor.Descriptor(
  name='PlaceholderRequest',
  full_name='PlaceholderRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='placeholder', full_name='PlaceholderRequest.placeholder', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=64,
)


_PLACEHOLDERREPLY = _descriptor.Descriptor(
  name='PlaceholderReply',
  full_name='PlaceholderReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='placeholder', full_name='PlaceholderReply.placeholder', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=105,
)

DESCRIPTOR.message_types_by_name['PlaceholderRequest'] = _PLACEHOLDERREQUEST
DESCRIPTOR.message_types_by_name['PlaceholderReply'] = _PLACEHOLDERREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlaceholderRequest = _reflection.GeneratedProtocolMessageType('PlaceholderRequest', (_message.Message,), {
  'DESCRIPTOR' : _PLACEHOLDERREQUEST,
  '__module__' : 'faucetconfrpc_pb2'
  # @@protoc_insertion_point(class_scope:PlaceholderRequest)
  })
_sym_db.RegisterMessage(PlaceholderRequest)

PlaceholderReply = _reflection.GeneratedProtocolMessageType('PlaceholderReply', (_message.Message,), {
  'DESCRIPTOR' : _PLACEHOLDERREPLY,
  '__module__' : 'faucetconfrpc_pb2'
  # @@protoc_insertion_point(class_scope:PlaceholderReply)
  })
_sym_db.RegisterMessage(PlaceholderReply)



_FAUCETCONFSERVER = _descriptor.ServiceDescriptor(
  name='FaucetConfServer',
  full_name='FaucetConfServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=107,
  serialized_end=182,
  methods=[
  _descriptor.MethodDescriptor(
    name='Placeholder',
    full_name='FaucetConfServer.Placeholder',
    index=0,
    containing_service=None,
    input_type=_PLACEHOLDERREQUEST,
    output_type=_PLACEHOLDERREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FAUCETCONFSERVER)

DESCRIPTOR.services_by_name['FaucetConfServer'] = _FAUCETCONFSERVER

# @@protoc_insertion_point(module_scope)
